### ISSUE TITLE
Player location is not accurate

### ISSUE THREAD

**Issue by Keith94** [dimotsai/agar-mini-map#1]
Firefox 41

Notice how the green square (me) goes outside the mini map. Also I don't know why there's a blue square on the mini map, seems like a bug.

![snag 2015 06 30 19 48 47](https://cloud.githubusercontent.com/assets/5490615/8446561/41df9f00-1f61-11e5-8ba7-bd05c66466c4.png)

**Comment by dimotsai** [comment]
@Keith Could you explain how to reproduce this bug? Also, thanks for your reporting.

**Comment by Keith94** [comment]
1. Install Firefox + Greasemonkey + your mini map script
4. Go to agar.io and play. Move around and watch the mini map. You should see your location on the mini map doesn't match your location on the actual grid, like its position is shifted over a lot, which causes it to go outside the borders of the mini map.

**Comment by dimotsai** [comment]
@Keith94 I made a change for it. Please check whether the mini map works properly.

**Comment by Keith94** [comment]
It's fixed! :) Thank you.
