### ISSUE TITLE
The minimap draws virus.

### ISSUE THREAD

**Issue by Estorva** [dimotsai/agar-mini-map#11]
It's weird that the minimap doesn't draw viruses in regular agar.io servers, but it does when it's ogar servers.

How does the minimap know when to ignore viruses? I looked into the code and found nothing about ignoring viruses.

**Comment by dimotsai** [comment]
@Estorva I think that is because ogar's implementation differs from agar.io. In fact, any node in the minimap is rendered only when it updates (x, y or size changes) more than twice. That's why foods are not rendered in the minimap.

**Comment by Estorva** [comment]
I still don't get it. What prevents the viruses (or nodes) from updating?

**Comment by dimotsai** [comment]
@Estorva The server itself prevents the viruses updating because that is unnecessary data transfer

**Comment by Estorva** [comment]
Well, 其實我想做的是把virus按照size上色（不曉得算不算作弊
我對code做了點修改（在讀取packet中遇到virus時就呼叫updatePos()），以目前的狀況而言如果我餵virus，顏色會變，但virus大到足以分裂時，顏色不會回到先前的狀態

這樣看來server不是在virus進入玩家視野時才update。如果server會update virus的size，那麼問題是出在哪裡...

**Comment by dimotsai** [comment]
一般 Server 在底下兩種情況會送資料過來：
1. size 變更
2. 進入視野或離開視野

Ogar Server 則是進入視野之後會一直送資料，不管 Virus 大小有沒有變

**Comment by dimotsai** [comment]
實際上 minimap 的 node color 是 `miniMapCreateToken` 就決定，但我沒設計 `miniMapUpdateToken` 可以更新顏色，所以就算有 call `updatePos` 顏色除非 node 離開視野再進來，不然顏色應該不會在更新，我想你的問題應該是這個。

**Comment by Estorva** [comment]
我是在 extractCellPacket 時就先記錄 isVirus（```isVirus = !!(k & 1)```），然後就是呼叫 updatePos()
```Javascript
if (!cells.hasOwnProperty(d) && isVirus) {
                k = new Cell(d, p, f, g, h, n, isVirus);
                ......
                k.updatePos();
            }
```
我讓 token 帶有 isVirus 這一項，這樣 minimap 在 render 的時候可以根據```token.isVirus```決定行為：
```Javascript
if (!token.isVirus)
    radarMapDrawCell(x_relat, y_relat, token.size, token.color, myRadMax, myRadMin, isMult, myCellNum);
else
    radarMapDrawVirus(x_relat, y_relat, radToMass(token.size));
```
在函數 radarMapDrawVirus 中根據```radToMass(token.size)```畫出 virus 顏色：
```Javascript
var r_v = ~~(250 - 50 * ratioDesc(size, 100, 200)), g_v = ~~(100 + 100 * ratioDesc(size, 100, 200));
...
rctx.fillStyle = 'rgb(' + r_v + ', ' + g_v + ', 0)';
```
而 virus 分裂的那一瞬間顏色（radarMapDrawVirus）不會改變，也就是 server 沒有 update。minimap 會畫出分裂出去的 virus，原本的 virus 卻要再餵他一次 server 才會 update（然後變回原來顏色）。
![agar mod](https://cloud.githubusercontent.com/assets/11908124/8824284/e5ff20aa-30a6-11e5-83ca-b3209d08581c.png)
右下的 minimap 中的菱形黃色物體就是 virus。

**Comment by dimotsai** [comment]
Insert the following code into your script:
```diff
diff --git a/agar-mini-map.user.js b/agar-mini-map.user.js
index 58bdec8..7362f7b 100644
--- a/agar-mini-map.user.js
+++ b/agar-mini-map.user.js
@@ -531,6 +531,10 @@ window.msgpack = this.msgpack;
                 }
             }

+            if (this.isVirus) {
+                 console.log(this.id, this.nSize);
+            }
+
             if (options.enablePosition && -1 != current_cell_ids.indexOf(this.id)) {
                 window.mini_map_pos.show();
                 miniMapUpdatePos(this.nx, this.ny);
@@ -657,6 +661,10 @@ window.msgpack = this.msgpack;
             k.updateTime = I;
             n && k.setName(n);

+            if (k.isVirus) {
+                 k.updatePos();
+            }
+
             // ignore food creation
             if (updated) {
                 dataToSend.nodes.push({

```
to see whether the viruses update or not.

**Comment by Estorva** [comment]
Yes it worked.

I have never thought to make it update twice that way, :P.
