### ISSUE TITLE
Error running server

### ISSUE THREAD

**Issue by Spyroh** [dimotsai/agar-mini-map#13]
I have downloaded the release v0.44 (agar-mini-map-v0.44-win-x64.zip), I have executed the install and build without any errors, but when I try to run the server I get this error:
![minimap server error](https://cloud.githubusercontent.com/assets/13414586/8772665/44dbb1cc-2ece-11e5-90ca-852287eb1059.png)
I'm using the following software:
- Windows 7 x64
- Node.js v0.12.7
- Python 2.7.10
- Microsoft NET Framework 2.0 SDK
- Microsoft Visual Studio Community 2015 RC

**Comment by dimotsai** [comment]
Try to remove node_modules and npm install again

Spyroh <notifications@github.com> 於 2015年7月20日週一 下午4:59 寫道：

**Comment by Spyroh** [comment]
Ok.
Here is the result of doing that:
![result](https://cloud.githubusercontent.com/assets/13414586/8774397/f1088a10-2edd-11e5-933a-5cb03671647d.png)

**Comment by dimotsai** [comment]
@Spyroh I am not sure whether VS2015 works well or not at the compiling process. But I have already done `npm install` and `npm run build` in the release `agar-mini-map-v0.44-win-x64.zip`, so you don't have do it again, just do `npm run start` and it should work. 

However, if you want to build the dependencies by your self, `VS2013` would be more suitable.

**Comment by Spyroh** [comment]
Oh ok, I didn't know that I could do the `npm run start` directly (I was just following the instructions on the **README.md**). I just want to run the server ASAP so I don't want to build anything myself if it's not needed.

Unfortunately if I do that (just unzip and `npm run start` on the server folder) I get exactly the same error on the screenshot on the first post. :-(

**Comment by dimotsai** [comment]
@Spyroh Is your nodejs x64 version?

**Comment by Spyroh** [comment]
I was using the x86 version (lol) that was the problem.
It runs perfectly now with just unzipping and `npm run start`.
Thx. :-)

**Comment by Salmonblubs** [comment]
I'm having the same problem. Btw see this and recommend me what to download:
![image](https://cloud.githubusercontent.com/assets/13907376/9415138/a6825b50-4856-11e5-85ba-1815316c81f9.png)

**Comment by dimotsai** [comment]
We currently don't support Windows 32-bit yet.

**Comment by Salmonblubs** [comment]
Oh, please do make it 32- bit.

**Comment by shon4than** [comment]
plz agar mini map in win-32bit plz :'c 
very many people use win-32 at need this map in the game
