### ISSUE TITLE
The client script fetch the incorrect address of agar server.

### ISSUE THREAD

**Issue by Lu0519** [dimotsai/agar-mini-map#15]
If you join party room
The IP sometimes get different IP, but in the same room
Therefore can't join together

**Comment by dimotsai** [comment]
@Lo0519 Is your client the latest version?

Lu0519 <notifications@github.com> 於 2015年7月21日週二 下午12:53 寫道：

**Comment by Lu0519** [comment]
Yes, the latest.
It seldom occurs, not so frequently.

But, there's one major bug:
In the middle part of the map, the information will be shown, and it's sometimes doesn't even exist one there.

**Comment by dimotsai** [comment]
@Lu0519 會不會是某些人的 Client 不是最新的，lag 的問題希望可以開另外一篇 issue，感謝你的回報。

**Comment by Lu0519** [comment]
不會哦，因為是我雙開，所以才覺得怪怪的 (只出現過一次，要出現也不是很容易)

**Comment by dimotsai** [comment]
我以為我修掉這個問題了，如果有重現 bug 的方法會比較容易找到問題在哪

Lu0519 <notifications@github.com> 於 2015年7月21日週二 下午8:13 寫道：

**Comment by Lu0519** [comment]
IP位置：目前不明，我在測試看看
中間球球：幾乎每場都會有這問題

**Comment by dimotsai** [comment]
不存在的球應該是疊到不同伺服器資料

Lu0519 <notifications@github.com> 於 2015年7月21日週二 下午8:18 寫道：

**Comment by Lu0519** [comment]
IP位置，可能問題：
自己自己 (127.0.0.1)，別人在連，會有這種現象

**Comment by dimotsai** [comment]
@Lu0519 https://gitter.im/dimotsai/agar-mini-map 即時討論，希望可以一同測試

**Comment by dimotsai** [comment]
It seems that one server may host multiple game rooms at the same time

**Comment by eve8** [comment]
Yes servers host multiple games at same time. Try to find correct one, minimap is working well...

**Comment by dimotsai** [comment]
@eve8 Is there any way to determine whether we are in the same game or not?

**Comment by eve8** [comment]
There is no way, unless you manually go to their location and if they are really there or not. Btw I don't know what they were thinking to host multiple servers on same IP. That's weird..

**Comment by davidmann4** [comment]
Sometimes it uses hostnames and sometimes ip

I guess this could be the problem - i just refresh the browser window and everything works.

**Comment by C0dePizza** [comment]
i've noticed that if you sign in with a linked facebook or google account, the client will make a secure websocket connection to wss://web-live-v3-0.agario.miniclippt.com/ws 

this leads the script into thinking this is the connection passing gameplay data, when it actually is just for account data (hence the ws<strong><em>S</em></strong>)

in my experience and in others, this seems to be the culprit. I started working on a fix for this and so far have just added a conditional to check for wss vs ws. if the url is secure, it will send the insecure address to the server instead.
