### ISSUE TITLE
An Error is repeating in my chrome console

### ISSUE THREAD

**Issue by blackphreak** [dimotsai/agar-mini-map#2]
I dont know why it comes...but when I installed your plugin, it will come and make a lot of error
Error: Uncaught TypeError: Cannot read property 'call' of null

*I found that error come from:
line: 440
        ws.onmessage = function(event) {
            extractPacket(event);
            return this.onmessage.call(ws, event);
        }.bind(this);

but the console said that it comes from line:444
line:444 is empty..so I think that is come from line: 440

hope you can help to fix it.

(sorry of my bad English)

**Comment by dimotsai** [comment]
@blackphreak Thanks for your report. Could you briefly explain how to reproduce this error? Does this error happen all the time?

**Comment by dimotsai** [comment]
@blackphreak Did you apply agar-mini-map on ogar servers or previous servers?
