### ISSUE TITLE
TIP: have vision over almost the whole minimap!

### ISSUE THREAD

**Issue by N1C39UY** [dimotsai/agar-mini-map#24]
hello, i wanted to share a nice trick. you can run a minimap server and open 2 tabs with agar then connect to the server with both in a party and for one of the accounts click spectate! now you have the spectate vision (wich is HUGE!!!) and your vision. good luck ;)

**Comment by dimotsai** [comment]
Yes, that is a good idea

**Comment by eve8** [comment]
Yea I've been using it but when you see so much stuff, it make the game more laggy, dunno why...
