### ISSUE TITLE
Creating server issue

### ISSUE THREAD

**Issue by nath626** [dimotsai/agar-mini-map#28]
I have installed Node.js and have tryed 

"cd agar-mini-map-v0.46-win-x64/server"
underneath I get 
SyntaxError: Unexpected identifier
   at Object.exports.createScript  (vm.js:44:10)
   at REPLServer.defaultEval  (repl.js:117:23)
   at bound  (domain.js:254:14)
   at REPLServer.runbound  [as eval]  (domain.js:267:12)
   at REPLServer.<anonymous>  (repl.js:279.12
   at REPLServer.emit  (events.js:107:17)
   at REPLServer.Interface._onLine  (readline.js:214:10
   at REPLServer.Interface._line  (readline.js:553:8)
   at REPLServer.Interface._ttyWrite  (readline.js:830:14)
   at Readstream.onkeypress  (readline.js:109:10)

I am running windows 10 and I made sure to install the 64 version of node.js

**Comment by dimotsai** [comment]
Please make sure that you operate with these commands under Windows Command
Prompt instead of Node Shell

**Comment by nath626** [comment]
when I try "cd agar-mini-map-v0.46-win-x64/server" in command prompt I get 
"The system cannot find the path specified I have the "zip" unzipped and on my desktop I used winrar to unzip it

**Comment by eve8** [comment]
1. Unzip
2. rename the file name something short, I say "1"
3. Copy Paste that file to the C:
4. Run node.js as an admin after you install
5. Run CMD as admin.
6. enter these commands; "cd.." enter, "cd.." enter, "cd server", enter "cd 1" enter, "npm start" enter.
6. don't forget to forward the port 34343.

@nath626

**Comment by nath626** [comment]
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:\\

c:\>cd 1

c:\1>cd server

c:\1\server>npm start

> mini-map-server@0.0.1 start c:\1\server
> node dist/server.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'c:\1\server\dist\server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! mini-map-server@0.0.1 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mini-map-server@0.0.1 start script 'node dist/server.js'.

npm ERR! This is most likely a problem with the mini-map-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mini-map-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\1\server\npm-debug.log

c:\1\server>

that's what my command prompt does

**Comment by nath626** [comment]
This is the debug log


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart mini-map-server@0.0.1
6 info start mini-map-server@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info mini-map-server@0.0.1 Failed to exec start script
9 verbose stack Error: mini-map-server@0.0.1 start: `node dist/server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid mini-map-server@0.0.1
11 verbose cwd c:\1\server
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error mini-map-server@0.0.1 start: `node dist/server.js`
17 error Exit status 1
18 error Failed at the mini-map-server@0.0.1 start script 'node dist/server.js'.
18 error This is most likely a problem with the mini-map-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node dist/server.js
18 error You can get their info via:
18 error     npm owner ls mini-map-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by dimotsai** [comment]
It's 'npm run start', not 'npm start'

**Comment by nath626** [comment]
I now feel retarded thx

**Comment by nath626** [comment]
Btw once it's on port 34343 It's just the server ws followed by port 34343 right?

**Comment by eve8** [comment]
npm start also works.

**Comment by nath626** [comment]
yep just tested it , it does
