### ISSUE TITLE
Server issues 

### ISSUE THREAD

**Issue by phatass69** [dimotsai/agar-mini-map#29]
Whenever I try to run with NodeJS I get the following error.

C:\server>npm start

> mini-map-server@0.0.1 start C:\server
> node dist/server.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\server\dist\server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! mini-map-server@0.0.1 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mini-map-server@0.0.1 start script 'node dist/server.js'.

npm ERR! This is most likely a problem with the mini-map-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mini-map-server
npm ERR! There is likely additional logging output above.

**Comment by eve8** [comment]
try to run node.js exe while u try again...

**Comment by nath626** [comment]
Phat I had the same issue

https://github.com/dimotsai/agar-mini-map/issues/28

Also do you have       Node_modules its a file in server

**Comment by nath626** [comment]
You also might have installed the wrong vesion of node.js and if you even want to use the mini-map server you need access to the router settings to port forward I use a http foward

**Comment by phatass69** [comment]
The problem ended up being that I had downloaded the source code. I downloaded the release version and it worked fine. Awesome agario add on btw.
