### ISSUE TITLE
minimap server guide is hard to understand

### ISSUE THREAD

**Issue by minutemail** [dimotsai/agar-mini-map#30]
1st small issue: the "windows" part does not include "npm install && npm run build" like the linux part.
2nd and most problematic:
"Now you can access your minimap server at ws://hostname:34343"
what is hostname?
when i start the server i can connect to it on multiple tabs with ws://127.0.0.1:34343
but my friend who is on a completely different network obviously cant use that ip.
what ip should i give him?
thanks

**Comment by eve8** [comment]
https://github.com/dimotsai/agar-mini-map/issues/31

**Comment by dimotsai** [comment]
@minutemail You should give your public IP address or [hostname](https://en.wikipedia.org/wiki/Hostname), such as `8.8.8.8` or `example.com`, instead of [localhost](https://en.wikipedia.org/wiki/Localhost) (i.e. 127.0.0.1).

For Windows, you can use the command `ipconfig` to see your public IP address, or visit  http://www.whatismyip.com/ to get your IP address. If your host is in a private network, port forwarding might be needed for the proper connection.

**Comment by minutemail** [comment]
to both of you - THANKS!
my port was indeed closed and i had to forward it.
one small question - do i need to run the commands
npm install
npm run build
everytime i want to run the server? or just once
obviously i need
npm run start
to start the server

**Comment by dimotsai** [comment]
No, you don't need to build every time

**Comment by kentakit** [comment]
how do i make the port-forwarding? 
http://www.yougetsignal.com/tools/open-ports/ with the portnumber 34343 tells me that it is closed.
There are different settings for the port-forwarding in my routersettings and i'm not able to understand anything.. Could you please help

**Comment by eve8** [comment]
Hello. Portforwarding is different for every modem-router. You should google for your modem. If you want, i can try to help you right now, https://tlk.io/agarchat

**Comment by kentakit** [comment]
Ok, i't works. The website tells me that the port is now open. But my public IP-adress (2004:6:33b:ff78:80c:57c9:cc2a:eb3b example) looks different from the typical adress.. and also it didn't work, if i put it like ws://publicIPadress:34343.
Also, i can connect with my hostname to my server but it's not possible for my friend (with ws://myhostname:34343)
