### ISSUE TITLE
Minimap Install Guide - Windows

### ISSUE THREAD

**Issue by eve8** [dimotsai/agar-mini-map#31]
1  Unzip
2  Rename the unzipped file name something short, I say "1"
3  Copy Paste that file to the somewhere for easy acces, I say C:
4  Run node.js as an admin after you install
5  Run CMD as admin.
6  Enter these CMD commands; "cd.." enter, "cd.." enter, "cd 1" enter, "cd server" enter, "npm start" enter.
7  Don't forget to forward the port 34343. Check your port if open while your server is running. http://www.yougetsignal.com/tools/open-ports/
8  Use your public ip to jonnect server. If you can connect with public ip, your friends also can.

**Comment by eskylo** [comment]
which version of node JS should I use?

**Comment by SentESp** [comment]
https://i.gyazo.com/8352253422ed04e6e162beae4d5a85b1.gif
Pls Help! D:
i'm on windows 10 x64
agar minimap version: v0.46
node version: v4.1.2-x64

**Comment by dimotsai** [comment]
@SentESp Please refer https://github.com/dimotsai/agar-mini-map/issues/45
