### ISSUE TITLE
I can't start the server

### ISSUE THREAD

**Issue by eskylo** [dimotsai/agar-mini-map#45]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart mini-map-server@0.0.1
6 info start mini-map-server@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info mini-map-server@0.0.1 Failed to exec start script
9 verbose stack Error: mini-map-server@0.0.1 start: `node dist/server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid mini-map-server@0.0.1
11 verbose cwd C:\Windows\System32\agar-mini-map-v0.46-win-x64\server
12 error Windows_NT 6.1.7600
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error mini-map-server@0.0.1 start: `node dist/server.js`
17 error Exit status 1
18 error Failed at the mini-map-server@0.0.1 start script 'node dist/server.js'.
18 error This is most likely a problem with the mini-map-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node dist/server.js
18 error You can get their info via:
18 error     npm owner ls mini-map-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
![sem titulo](https://cloud.githubusercontent.com/assets/8031138/9805484/d3824ff2-580f-11e5-88cc-ba7f3395884d.png)

**Comment by AxDSan** [comment]
It's happening to me too :(

**Comment by dimotsai** [comment]
@eskylo Make sure your that operating system is 64-bit and contains 64-bit NodeJS

**Comment by AxDSan** [comment]
@dimotsai ![Image of my NodeJS](http://i.imgur.com/a8MjkTE.png)

**Comment by dimotsai** [comment]
@AxDSan @eskylo
OK. I see the problem. NodeJS version varies recently. I wrote the server in NodeJS v0.12.7. I will release the new version.

**Comment by AxDSan** [comment]
@dimotsai AwesomeSauce :D Thanks :+1:  Really appreciated

**Comment by dimotsai** [comment]
The dependency msgpack is out of date right now. I am looking for alternatives. For temporary usage, you can download [the old NodeJS](https://nodejs.org/download/release/latest-v0.12.x/x64/).

**Comment by dimotsai** [comment]
https://github.com/pgriess/node-msgpack/issues/63

**Comment by AxDSan** [comment]
@dimotsai Perfect, thanks for the updates, Will get the older version of NodeJS then :D :+1:

**Comment by AxDSan** [comment]
Update on Alternative Solution (Use Old NodeJS):
it gives me this now, I don't know if I'm now doing something wrong on my end?
![Old NodeJS New Error](http://i.imgur.com/IHDFSlQ.png)

**Comment by eskylo** [comment]
It worked! Using the old node Js (https://nodejs.org/download/release/latest-v0.12.x/x64/)

Thank you very much, dimotsai. For the patience and awesome job creating this.

![sem titulo](https://cloud.githubusercontent.com/assets/8031138/9866700/02976ba4-5b3c-11e5-851f-a7b298008a21.png)

**Comment by AxDSan** [comment]
Fixed too: Working perfectly now :dancer: 
![Server Working](http://i.imgur.com/cfXc2ih.png)
