### ISSUE TITLE
how do i connect to a minmap

### ISSUE THREAD

**Issue by Agar09** [dimotsai/agar-mini-map#46]
my friend on the same WiFi has created a mini-map and opened the port 34343
where on different pc's but everytime i connect to 127.0.0.1:34343 it automatically disconnects. how can we both connect to the same mini map?

**Comment by dimotsai** [comment]
127.0.0.1 represents the [localhost](
https://en.m.wikipedia.org/wiki/Localhost). This means your friend will
connect his/her own PC when he/she is trying to connect 127.0.0.1

Agar09 <notifications@github.com> 於 2015年9月22日週二 上午2:22 寫道：

**Comment by Agar09** [comment]
So how do I connect to it?

**Comment by Agar09** [comment]
How do I find out what the client needs to connect to on the same party

**Comment by dimotsai** [comment]
http://www.whatismyip.com/
