### ISSUE TITLE
How to install on Windows x32?

### ISSUE THREAD

**Issue by OthonGBR** [dimotsai/agar-mini-map#47]
Already tried everything to install on Windows x32 but could not. Is giving error!

Error:
![error 1](https://cloud.githubusercontent.com/assets/14895784/10176406/dc3b6a60-66ca-11e5-92cb-e99ba0474071.png)
![error 2](https://cloud.githubusercontent.com/assets/14895784/10176405/dc3b5890-66ca-11e5-9706-fccfab7e33ed.png)

**Comment by dimotsai** [comment]
Currently, don't support Windows 32-bit yet
