### ISSUE TITLE
Cant get it working...

### ISSUE THREAD

**Issue by XAVIER77** [dimotsai/agar-mini-map#48]
When I copy and paste this(cd agar-mini-map-<version>-win-x64/server
npm run start) it says this.
Your environment has been set up for using Node.js 0.12.7 (x64) and npm.

C:\Users\Jacques>

C:\Users\Jacques>
C:\Users\Jacques>cd agar-mini-map-<version>-win-x64/server
The system cannot find the file specified.

C:\Users\Jacques>npm run start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\Jacques\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\Jacques\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jacques\npm-debug.log

C:\Users\Jacques>

**Comment by dimotsai** [comment]
Seems like you are not in the right directory(C:\Users\Jacques). Please make sure that you change to the mini-map directory. (`cd` stands for `change directory`) After that, you run `npm run start`.

**Comment by XAVIER77** [comment]
Damn, I don't think I am doing it right, I still get problems, probably don't really know how to do that...I am very stupid when it comes to this kind of stuff.
