### ISSUE TITLE
How do you make a party with yourself (multiboxing) without making a server?

### ISSUE THREAD

**Issue by Raider3030** [dimotsai/agar-mini-map#49]
I would like to make a party to multibox but i don't know how to make a server to share vision is there a way to do it localy without making a server? Also the ip that is already there when i try to connect to it, it just disconnects me right away.

**Comment by dimotsai** [comment]
@Raider3030 
No, due to the browser restriction, you can not share data between tabs with a server. The only way is to create a server locally and both tabs connect to the local server.

**Comment by Raider3030** [comment]
Okay thanks I can't make a server but cool minimap!
