### ISSUE TITLE
No points when using this script

### ISSUE THREAD

**Issue by lenisko** [dimotsai/agar-mini-map#52]
Hmm there is no points for play, when using this script.

**Comment by dimotsai** [comment]
@lenisko Sorry, I don't understand what you really mean. Could you explain the situation more specifically?

**Comment by lenisko** [comment]
Okay, sorry for that, let me correct myself.

So lets assume __I'm not using this script__ I am starting agar.io, some time playing, someone eated me, window with score is show, points are added to logged account.

And now __using this script__ caused agar to not showing window with score, also points for play are not added to account.

**Comment by dimotsai** [comment]
I have tried playing with the script, but I did have a popup window counting points after my cells got eaten. I wonder if you have installed other scripts or plugins. That would be helpful to address the problem if you could provide those plugins.

**Comment by lenisko** [comment]
Thats weird... I am using:
__Firefox Beta__ 43.0b6
__Greasemonkey__ 3.6
And your last commited script on GitHub.

uBlock disabled, all other userscripts disabled too on agar.io, and yet no popup window nor points.

**Comment by agariominimap** [comment]
lenisko is right. Sometimes it does not work. The player receives no points.
Also some cells(including your own cell) stays forever on the screen where they were eaten before. It is a big problem too.

**Comment by dimotsai** [comment]
@lenisko I see, I tested on Chrome. I will test on other browers

**Comment by dimotsai** [comment]
@lenisko Does the problem happens also on Chrome?

**Comment by lenisko** [comment]
I don't have Chrome, but.. it's working on Vivaldi with Tampermonkey.
So I am assuming, that is Firefox related problem.

**Comment by dimotsai** [comment]
Tested it again on OS X 10.11.1, everything works pretty well on Firefox 41.2, Chrome 46.0.2490.86 and Safari 9.0.1. Looks like that Firefox on Windows in the only victim.

PS. In fact, the points are already being counted in the background. But the window does not show up unless you hit the `ESC` button.

**Comment by lenisko** [comment]
Ohh... I didn't know about ESC. Hmm... maybe for workaround there is a way to simulate pressing button, after getting eaten?
