### ISSUE TITLE
wrong information on both main and map screen

### ISSUE THREAD

**Issue by agrplayer** [dimotsai/agar-mini-map#54]
After playing a while it starts showing up wrong information.
The cells which should of been disappeared stays on the screen including own cells. For instance, when splitted cell merges, the splitted old part stays on the screen. Examples can be increased. Basically old parts stay on the screen.
This happens on both firefox and chrome browsers.

**Comment by agrplayer** [comment]
![canvas](https://cloud.githubusercontent.com/assets/16148501/11591773/fe2c8d6e-9aa2-11e5-9abe-04d85a8d4d6c.png)

This is what happens after a long while on spectater mode, it is the same on any game mode.

**Comment by dimotsai** [comment]
@agrplayer I didn't see the minimap from your screenshot

**Comment by agrplayer** [comment]
it is because its taken by right clicking and choosing "save as" on firefox.

**Comment by agrplayer** [comment]
This is what happens after 20 minutes on spectate mode but its the same on any game mode.
Perhaps one other problem the mini map also stops working frequently. It starts working  after pressing connect as in the second picture.
![capture](https://cloud.githubusercontent.com/assets/16148501/11612663/a74efd0a-9c0b-11e5-8022-c1087760b9a6.JPG)
![capture2](https://cloud.githubusercontent.com/assets/16148501/11612664/ab046c32-9c0b-11e5-98f8-adcd7e97c390.JPG)

**Comment by dimotsai** [comment]
@agrplayer Thanks for the reporting. This issue has been confirmed. The packet structure changed because the skin module is added. I have already updated the script. Could you help me test it?

**Comment by agrplayer** [comment]
Thx, i have just checked, its fixed.
