### ISSUE TITLE
cant continue play the same game .. i have to press f5 or refresh which mean session is lost if it was interesting.. 

### ISSUE THREAD

**Issue by aero9** [dimotsai/agar-mini-map#68]
if the script is  running and cell has been eaten, my browser fail to display the elements of new game .
couple of basic tools does not show up , the screen sized transparent  overlay is not there, the progress bar on status bar  get loaded in no time  and any redirect stop but  agario does not show the last score board options and other stuff to start new game  .

my browser is old firefox 26.0~linux system  but your script  used to work without interfering.

hope i get some help

**Comment by dimotsai** [comment]
See https://github.com/dimotsai/agar-mini-map/issues/52
But currently the script is not working due to the map size obfuscation

**Comment by aero9** [comment]
thank you dimotsai , yeah esc help in my situation .
