### ISSUE TITLE
Server would crash if we use the script manually

### ISSUE THREAD

**Issue by domen111** [dimotsai/agar-mini-map#9]
Sorry, I found the way of installing the script manually which I used is wrong. And it will make the server crash. Doesn't the server have a protection? Or it is a bug?
![image](https://cloud.githubusercontent.com/assets/8273087/8762416/d35fa2c0-2daa-11e5-8d07-b560ab3b878d.png)

**Comment by dimotsai** [comment]
@domen111 You have to re-select server to make it work. Otherwise the url will be null and it crashes the server. But yes, that is a bug, I did not check the packet which is sent from clients.
